# [default]
# aws_access_key_id = "SEU_ACCESS_KEY_ID"
# aws_secret_access_key = "SEU_SECRET_ACCESS_KEY"
# bucket_name = "seu-nome-do-bucket"

# Configurações da AWS
AWS_ACCESS_KEY_ID=your_aws_access_key_id
AWS_SECRET_ACCESS_KEY=your_aws_secret_access_key

# Configurações do Oracle Cloud
ORACLE_KEY_FILE=/path/to/your/oracle/key_file.pem
ORACLE_BUCKET_NAME=your_oracle_bucket_name
ORACLE_NAMESPACE=your_oracle_namespace

# Configurações do Google Cloud
GOOGLE_CREDENTIALS_FILE=/path/to/your/google/credentials.json
GOOGLE_BUCKET_NAME=your_google_bucket_name